package org.ctl.parquet

import net.andreinc.mockneat.MockNeat
import net.andreinc.mockneat.MockNeat._
import net.andreinc.mockneat.types.enums.StringFormatType

object Model {
  val mockNeat = MockNeat.threadLocal()
  import mockNeat._

  import net.andreinc.mockneat.abstraction.MockUnitString

  val addressGenerator: MockUnitString =
    fmt("#{nr} #{adj}#{noun} #{suffix}")
      .param("adj", probabilites(classOf[String])
      .add(0.25, words()
        .adjectives()
        .format(StringFormatType.CAPITALIZED)
        .append(" ")
      )
        .add(0.75, "")
        .mapToString()
      )
      .param("noun", words().nouns().format(StringFormatType.CAPITALIZED))
        .param("suffix", probabilites(classOf[String])
      .add(0.25, "Lane")
        .add(0.25, "Blvd.")
        .add(0.50, "Street")
        .mapToString())
      .param("nr", ints().range(1, 600))

  def main(args: Array[String]):Unit = {
    println( American.random() )
  }
}


//{
//case class American(firstName:String, lastName:String, addressId:Int, irrelevantP1:String, irrelevantP100:String)
//case class Address(id:Int, street:String, city:String, irrelevantA1:String, irrelevantA100:String)
//case class HumanoidLivingSomewhere(called:String, alsoCalled: String, whereHeLives_id:Int)
//}

case class BoringOrder(sku:Int, name:String, price: BigDecimal)

case class SuperOrder(sku:Int, name:String, price: BigDecimal, irrelevantP1:String, irrelevantP2:String, irrelevantP3:String, irrelevantP4:String, irrelevantP5:String, irrelevantP6:String, irrelevantP7:String, irrelevantP8:String, irrelevantP9:String, irrelevantP10:String, irrelevantP11:String, irrelevantP12:String, irrelevantP13:String, irrelevantP14:String, irrelevantP15:String, irrelevantP16:String, irrelevantP17:String, irrelevantP18:String, irrelevantP19:String, irrelevantP20:String, irrelevantP21:String, irrelevantP22:String, irrelevantP23:String, irrelevantP24:String, irrelevantP25:String, irrelevantP26:String, irrelevantP27:String, irrelevantP28:String, irrelevantP29:String, irrelevantP30:String, irrelevantP31:String, irrelevantP32:String, irrelevantP33:String, irrelevantP34:String, irrelevantP35:String, irrelevantP36:String, irrelevantP37:String, irrelevantP38:String, irrelevantP39:String, irrelevantP40:String, irrelevantP41:String, irrelevantP42:String, irrelevantP43:String, irrelevantP44:String, irrelevantP45:String, irrelevantP46:String, irrelevantP47:String, irrelevantP48:String, irrelevantP49:String, irrelevantP50:String, irrelevantP51:String, irrelevantP52:String, irrelevantP53:String, irrelevantP54:String, irrelevantP55:String, irrelevantP56:String, irrelevantP57:String, irrelevantP58:String, irrelevantP59:String, irrelevantP60:String, irrelevantP61:String, irrelevantP62:String, irrelevantP63:String, irrelevantP64:String, irrelevantP65:String, irrelevantP66:String, irrelevantP67:String, irrelevantP68:String, irrelevantP69:String, irrelevantP70:String, irrelevantP71:String, irrelevantP72:String, irrelevantP73:String, irrelevantP74:String, irrelevantP75:String, irrelevantP76:String, irrelevantP77:String, irrelevantP78:String, irrelevantP79:String, irrelevantP80:String, irrelevantP81:String, irrelevantP82:String, irrelevantP83:String, irrelevantP84:String, irrelevantP85:String, irrelevantP86:String, irrelevantP87:String, irrelevantP88:String, irrelevantP89:String, irrelevantP90:String, irrelevantP91:String, irrelevantP92:String, irrelevantP93:String, irrelevantP94:String, irrelevantP95:String, irrelevantP96:String, irrelevantP97:String, irrelevantP98:String, irrelevantP99:String, irrelevantP100:String)
object SuperOrder {
  import Model.mockNeat._
  val name = words().verbs().get() + "-" + words().nouns().get
  val sku = name.hashCode()
  def random() = SuperOrder(
    sku, name, BigDecimal(doubles().range(1.00, 1000.00).get()),
    strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get()
  )
}


case class American(firstName:String, lastName:String, address_id:Int, irrelevantP1:String, irrelevantP2:String, irrelevantP3:String, irrelevantP4:String, irrelevantP5:String, irrelevantP6:String, irrelevantP7:String, irrelevantP8:String, irrelevantP9:String, irrelevantP10:String, irrelevantP11:String, irrelevantP12:String, irrelevantP13:String, irrelevantP14:String, irrelevantP15:String, irrelevantP16:String, irrelevantP17:String, irrelevantP18:String, irrelevantP19:String, irrelevantP20:String, irrelevantP21:String, irrelevantP22:String, irrelevantP23:String, irrelevantP24:String, irrelevantP25:String, irrelevantP26:String, irrelevantP27:String, irrelevantP28:String, irrelevantP29:String, irrelevantP30:String, irrelevantP31:String, irrelevantP32:String, irrelevantP33:String, irrelevantP34:String, irrelevantP35:String, irrelevantP36:String, irrelevantP37:String, irrelevantP38:String, irrelevantP39:String, irrelevantP40:String, irrelevantP41:String, irrelevantP42:String, irrelevantP43:String, irrelevantP44:String, irrelevantP45:String, irrelevantP46:String, irrelevantP47:String, irrelevantP48:String, irrelevantP49:String, irrelevantP50:String, irrelevantP51:String, irrelevantP52:String, irrelevantP53:String, irrelevantP54:String, irrelevantP55:String, irrelevantP56:String, irrelevantP57:String, irrelevantP58:String, irrelevantP59:String, irrelevantP60:String, irrelevantP61:String, irrelevantP62:String, irrelevantP63:String, irrelevantP64:String, irrelevantP65:String, irrelevantP66:String, irrelevantP67:String, irrelevantP68:String, irrelevantP69:String, irrelevantP70:String, irrelevantP71:String, irrelevantP72:String, irrelevantP73:String, irrelevantP74:String, irrelevantP75:String, irrelevantP76:String, irrelevantP77:String, irrelevantP78:String, irrelevantP79:String, irrelevantP80:String, irrelevantP81:String, irrelevantP82:String, irrelevantP83:String, irrelevantP84:String, irrelevantP85:String, irrelevantP86:String, irrelevantP87:String, irrelevantP88:String, irrelevantP89:String, irrelevantP90:String, irrelevantP91:String, irrelevantP92:String, irrelevantP93:String, irrelevantP94:String, irrelevantP95:String, irrelevantP96:String, irrelevantP97:String, irrelevantP98:String, irrelevantP99:String, irrelevantP100:String)
object American {
  import Model.mockNeat._
  def random() = American(
    names().first().get(), names().last().get(), ints().range(1, 30).get(),
    strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get()
  )
}

case class Canadian(name:String, surname:String, residenceId:Int, irrelevantP1:String, irrelevantP2:String, irrelevantP3:String, irrelevantP4:String, irrelevantP5:String, irrelevantP6:String, irrelevantP7:String, irrelevantP8:String, irrelevantP9:String, irrelevantP10:String, irrelevantP11:String, irrelevantP12:String, irrelevantP13:String, irrelevantP14:String, irrelevantP15:String, irrelevantP16:String, irrelevantP17:String, irrelevantP18:String, irrelevantP19:String, irrelevantP20:String, irrelevantP21:String, irrelevantP22:String, irrelevantP23:String, irrelevantP24:String, irrelevantP25:String, irrelevantP26:String, irrelevantP27:String, irrelevantP28:String, irrelevantP29:String, irrelevantP30:String, irrelevantP31:String, irrelevantP32:String, irrelevantP33:String, irrelevantP34:String, irrelevantP35:String, irrelevantP36:String, irrelevantP37:String, irrelevantP38:String, irrelevantP39:String, irrelevantP40:String, irrelevantP41:String, irrelevantP42:String, irrelevantP43:String, irrelevantP44:String, irrelevantP45:String, irrelevantP46:String, irrelevantP47:String, irrelevantP48:String, irrelevantP49:String, irrelevantP50:String, irrelevantP51:String, irrelevantP52:String, irrelevantP53:String, irrelevantP54:String, irrelevantP55:String, irrelevantP56:String, irrelevantP57:String, irrelevantP58:String, irrelevantP59:String, irrelevantP60:String, irrelevantP61:String, irrelevantP62:String, irrelevantP63:String, irrelevantP64:String, irrelevantP65:String, irrelevantP66:String, irrelevantP67:String, irrelevantP68:String, irrelevantP69:String, irrelevantP70:String, irrelevantP71:String, irrelevantP72:String, irrelevantP73:String, irrelevantP74:String, irrelevantP75:String, irrelevantP76:String, irrelevantP77:String, irrelevantP78:String, irrelevantP79:String, irrelevantP80:String, irrelevantP81:String, irrelevantP82:String, irrelevantP83:String, irrelevantP84:String, irrelevantP85:String, irrelevantP86:String, irrelevantP87:String, irrelevantP88:String, irrelevantP89:String, irrelevantP90:String, irrelevantP91:String, irrelevantP92:String, irrelevantP93:String, irrelevantP94:String, irrelevantP95:String, irrelevantP96:String, irrelevantP97:String, irrelevantP98:String, irrelevantP99:String, irrelevantP100:String)
object Canadian {
  import Model.mockNeat._
  def random() = Canadian(
    names().first().get(), names().last().get(), ints().range(1, 30).get(),
    strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get()
  )
}

case class Yeti(gruntingSound:String, roaringSound:String, caveId:Int, irrelevantP1:String, irrelevantP2:String, irrelevantP3:String, irrelevantP4:String, irrelevantP5:String, irrelevantP6:String, irrelevantP7:String, irrelevantP8:String, irrelevantP9:String, irrelevantP10:String, irrelevantP11:String, irrelevantP12:String, irrelevantP13:String, irrelevantP14:String, irrelevantP15:String, irrelevantP16:String, irrelevantP17:String, irrelevantP18:String, irrelevantP19:String, irrelevantP20:String, irrelevantP21:String, irrelevantP22:String, irrelevantP23:String, irrelevantP24:String, irrelevantP25:String, irrelevantP26:String, irrelevantP27:String, irrelevantP28:String, irrelevantP29:String, irrelevantP30:String, irrelevantP31:String, irrelevantP32:String, irrelevantP33:String, irrelevantP34:String, irrelevantP35:String, irrelevantP36:String, irrelevantP37:String, irrelevantP38:String, irrelevantP39:String, irrelevantP40:String, irrelevantP41:String, irrelevantP42:String, irrelevantP43:String, irrelevantP44:String, irrelevantP45:String, irrelevantP46:String, irrelevantP47:String, irrelevantP48:String, irrelevantP49:String, irrelevantP50:String, irrelevantP51:String, irrelevantP52:String, irrelevantP53:String, irrelevantP54:String, irrelevantP55:String, irrelevantP56:String, irrelevantP57:String, irrelevantP58:String, irrelevantP59:String, irrelevantP60:String, irrelevantP61:String, irrelevantP62:String, irrelevantP63:String, irrelevantP64:String, irrelevantP65:String, irrelevantP66:String, irrelevantP67:String, irrelevantP68:String, irrelevantP69:String, irrelevantP70:String, irrelevantP71:String, irrelevantP72:String, irrelevantP73:String, irrelevantP74:String, irrelevantP75:String, irrelevantP76:String, irrelevantP77:String, irrelevantP78:String, irrelevantP79:String, irrelevantP80:String, irrelevantP81:String, irrelevantP82:String, irrelevantP83:String, irrelevantP84:String, irrelevantP85:String, irrelevantP86:String, irrelevantP87:String, irrelevantP88:String, irrelevantP89:String, irrelevantP90:String, irrelevantP91:String, irrelevantP92:String, irrelevantP93:String, irrelevantP94:String, irrelevantP95:String, irrelevantP96:String, irrelevantP97:String, irrelevantP98:String, irrelevantP99:String, irrelevantP100:String)
object Yeti {
  import Model.mockNeat._
  def random() = Yeti(
    names().first().get(), names().last().get(), ints().range(1, 30).get(),
    strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get()
  )
}

case class Address(id:Int, street:String, city:String, current: Boolean, irrelevantA1:String, irrelevantA2:String, irrelevantA3:String, irrelevantA4:String, irrelevantA5:String, irrelevantA6:String, irrelevantA7:String, irrelevantA8:String, irrelevantA9:String, irrelevantA10:String, irrelevantA11:String, irrelevantA12:String, irrelevantA13:String, irrelevantA14:String, irrelevantA15:String, irrelevantA16:String, irrelevantA17:String, irrelevantA18:String, irrelevantA19:String, irrelevantA20:String, irrelevantA21:String, irrelevantA22:String, irrelevantA23:String, irrelevantA24:String, irrelevantA25:String, irrelevantA26:String, irrelevantA27:String, irrelevantA28:String, irrelevantA29:String, irrelevantA30:String, irrelevantA31:String, irrelevantA32:String, irrelevantA33:String, irrelevantA34:String, irrelevantA35:String, irrelevantA36:String, irrelevantA37:String, irrelevantA38:String, irrelevantA39:String, irrelevantA40:String, irrelevantA41:String, irrelevantA42:String, irrelevantA43:String, irrelevantA44:String, irrelevantA45:String, irrelevantA46:String, irrelevantA47:String, irrelevantA48:String, irrelevantA49:String, irrelevantA50:String, irrelevantA51:String, irrelevantA52:String, irrelevantA53:String, irrelevantA54:String, irrelevantA55:String, irrelevantA56:String, irrelevantA57:String, irrelevantA58:String, irrelevantA59:String, irrelevantA60:String, irrelevantA61:String, irrelevantA62:String, irrelevantA63:String, irrelevantA64:String, irrelevantA65:String, irrelevantA66:String, irrelevantA67:String, irrelevantA68:String, irrelevantA69:String, irrelevantA70:String, irrelevantA71:String, irrelevantA72:String, irrelevantA73:String, irrelevantA74:String, irrelevantA75:String, irrelevantA76:String, irrelevantA77:String, irrelevantA78:String, irrelevantA79:String, irrelevantA80:String, irrelevantA81:String, irrelevantA82:String, irrelevantA83:String, irrelevantA84:String, irrelevantA85:String, irrelevantA86:String, irrelevantA87:String, irrelevantA88:String, irrelevantA89:String, irrelevantA90:String, irrelevantA91:String, irrelevantA92:String, irrelevantA93:String, irrelevantA94:String, irrelevantA95:String, irrelevantA96:String, irrelevantA97:String, irrelevantA98:String, irrelevantA99:String, irrelevantA100:String)
object Address {
  import Model.mockNeat._
  def random() = Address(
    ints().range(1, 30).get(), Model.addressGenerator.get(), cities().us().get(),
    bools().probability(0.50).get(),
    strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get(), strings().size(5).get()
  )
}


case class HumanoidLivingSomewhere(called:String, alsoCalled: String, whereHeLives_id:Int)


